#!/usr/bin/env python3
"""Build an l_rf_offset table (lladkine.param syntax) from get_RF_offset_fit.C per-run results.

usage: python3 lad_rf_offset_table.py <rf_offset_results.root> <out.param> [--tol 0.05] [--min-n 2000] [--max-jitter 0.7]

Per run and arm the phase is the get_RF_offset_fit.C value (peak of fmod(t_vertex - RF, T));
rf_offset = -phase. A run's value is used only if
  - its mod histogram has >= --min-n entries,
  - its raw t_vertex - RF histogram is not a single value (rms > 0; replays without
    t_vertex or RF give all-zero entries, which the fit turns into ~1.58 ns),
  - the RF comb is present: Gaussian-equivalent circular width of the mod histogram
    < --max-jitter ns (runs whose vertex timing is broken have a flat phase).
Rows are emitted at the first run of the data and wherever a usable value of either arm
differs from the current row by more than --tol ns (so single-run flips get their own
row and a row back). An arm without a usable value carries the previous row forward
(its t_vertex is missing or broken, so the RF correction does not matter for it).
Rows are applied by THcLADKine as run_start (a row holds until the next row's run).
"""
import argparse
import math

import numpy as np
import ROOT

ROOT.gROOT.SetBatch(True)
ROOT.gErrorIgnoreLevel = ROOT.kError
T = 4.00801


def rem(x):
    return (x + T / 2) % T - T / 2


def read(path):
    f = ROOT.TFile.Open(path)
    out = {}
    for s in ("P", "H"):
        g = [o for o in f.Get("c_offsets_" + s).GetListOfPrimitives() if o.InheritsFrom("TGraph")][0]
        val = {int(round(g.GetPointX(i))): g.GetPointY(i) for i in range(g.GetN())}
        for k in f.Get("h_mod_" + s).GetListOfKeys():
            r = int(k.GetName().split("_")[-1])
            hm = [o for o in k.ReadObj().GetListOfPrimitives() if o.InheritsFrom("TH1")][0]
            n = hm.GetNbinsX()
            c = np.array([hm.GetBinContent(i) for i in range(1, n + 1)])
            x = np.array([hm.GetBinCenter(i) for i in range(1, n + 1)])
            raw = f.Get(f"h_{s}/h_{s}_{r}")
            R = 0.0
            if c.sum() > 0:
                a = 2 * np.pi * x / T
                R = math.hypot((c * np.cos(a)).sum(), (c * np.sin(a)).sum()) / c.sum()
            jit = T / 2 / np.pi * math.sqrt(-2 * math.log(R)) if 0 < R < 1 else (0.0 if R >= 1 else 99.)
            out.setdefault(r, {})[s] = dict(v=val.get(r, float("nan")), n=c.sum(), rawrms=raw.GetRMS() if raw else 0.,
                                            jit=jit)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("infile")
    ap.add_argument("outfile")
    ap.add_argument("--tol", type=float, default=0.05)
    ap.add_argument("--min-n", type=float, default=2000)
    ap.add_argument("--max-jitter", type=float, default=0.7)
    a = ap.parse_args()
    d = read(a.infile)
    runs = sorted(d)

    def usable(r, s):
        q = d[r].get(s)
        if not q or not np.isfinite(q["v"]):
            return None, "no fit"
        if q["n"] < a.min_n:
            return None, f"n={q['n']:.0f}"
        if q["rawrms"] <= 0:
            return None, "t_vertex-RF identically constant (missing t_vertex/RF in that replay)"
        if q["jit"] > a.max_jitter:
            return None, f"no RF comb (width {q['jit']:.2f} ns)"
        return q["v"] % T, ""

    rows, rejected = [], []
    cur = {"P": None, "H": None}
    for r in runs:
        new = dict(cur)
        changed = False
        for s in ("P", "H"):
            v, why = usable(r, s)
            if v is None:
                if why != "no fit" and not why.startswith("n="):
                    rejected.append((r, s, d[r][s]["v"], why))
                continue
            if cur[s] is None or abs(rem(v - cur[s])) > a.tol:
                new[s] = v
                changed = True
        if changed:
            # fill an arm never measured so far with the first usable value later on (handled below)
            rows.append([r, new["P"], new["H"]])
            cur = new
    # back-fill leading None values with the first known value of that arm
    for i, s in ((1, "P"), (2, "H")):
        first = next((row[i] for row in rows if row[i] is not None), 0.0)
        for row in rows:
            if row[i] is None:
                row[i] = first
            else:
                break

    with open(a.outfile, "w") as fo:
        fo.write(f"; l_rf_offset generated by lad_rf_offset_table.py from {a.infile}\n")
        fo.write(f"; tol {a.tol} ns, min entries {a.min_n:.0f}, max comb width {a.max_jitter} ns.\n")
        fo.write("; Rows apply from run_start until the next row. rf_offset = -(peak of fmod(t_vertex - RF, T)).\n")
        fo.write(f"l_nr_rf_offsets = {len(rows)}\n")
        fo.write(";               run_start       SHMS        HMS\n")
        for i, (r, p, h) in enumerate(rows):
            lead = "l_rf_offset =   " if i == 0 else "                "
            fo.write(f"{lead}{r},          {-p:6.3f},     {-h:6.3f}{',' if i < len(rows) - 1 else ''}\n")
        fo.write("\n; Runs/arms whose measurement was not used:\n")
        for r, s, v, why in rejected:
            fo.write(f";   {r} {s}  fit {v:6.3f}  -- {why}\n")
    print(f"{len(rows)} rows written to {a.outfile}; {len(rejected)} run/arm measurements rejected")


if __name__ == "__main__":
    main()
