# Generated automatically from Makefile.in by configure.
# This Makefile is used to create several test cases for Tcl's load
# command.  It also illustrates how to take advantage of configuration
# exported by Tcl to set up Makefiles for shared libraries.
# RCS: @(#) $Id: Makefile.in,v 1.6 1999/09/21 06:37:32 hobbs Exp $

TCL_DBGX =		
CC = cc
SCALERLIBS = -L../../coda2/crl2.2.1/RPC -lscaser
#LIBS =			-L/usr/local/src/tcl8.3.1/unix -ltclstub8.3${TCL_DBGX}\
#		 -ldl  -lsocket -lnsl -lm $(SCALERLIBS) -lc
TCL_DIR=/apps/tcl/tcl8.3.4/tcl8.3.4

LIBS =			-L$(TCL_DIR)/unix -ltclstub8.3${TCL_DBGX}\
		 -ldl  -lsocket -lnsl -lm $(SCALERLIBS) -lc

AC_FLAGS =		
SHLIB_CFLAGS =		-KPIC
SHLIB_LD =		/usr/ccs/bin/ld -G -z text
SHLIB_SUFFIX =		.so
SHLIB_VERSION =		
SRC_DIR =		.
TCL_VERSION=		8.3

CFLAGS = -g
#CC_SWITCHES = $(CFLAGS) -I${SRC_DIR}/../../generic -DTCL_MEM_DEBUG \
#	${SHLIB_CFLAGS} -DUSE_TCL_STUBS ${AC_FLAGS} -I./include

CC_SWITCHES = $(CFLAGS) -I$(TCL_DIR)/generic -DTCL_MEM_DEBUG \
	${SHLIB_CFLAGS} -DUSE_TCL_STUBS ${AC_FLAGS} -I./include

all: pkga${SHLIB_SUFFIX} pkgb${SHLIB_SUFFIX} scaler${SHLIB_SUFFIX}

pkga${SHLIB_SUFFIX}: $(SRC_DIR)/pkga.c
	$(CC) -c $(CC_SWITCHES) $(SRC_DIR)/pkga.c
	${SHLIB_LD} -o pkga${SHLIB_SUFFIX} pkga.o ${LIBS}

pkgb${SHLIB_SUFFIX}: $(SRC_DIR)/pkgb.c
	$(CC) -c $(CC_SWITCHES) $(SRC_DIR)/pkgb.c
	${SHLIB_LD} -o pkgb${SHLIB_SUFFIX} pkgb.o ${LIBS}

scaler${SHLIB_SUFFIX}: $(SRC_DIR)/scaler.c
	$(CC) -c $(CC_SWITCHES) $(SRC_DIR)/scaler.c
	${SHLIB_LD} -o scaler${SHLIB_SUFFIX} scaler.o ${LIBS}

clean:
	rm -f *.o *${SHLIB_SUFFIX} config.cache config.log config.status lib.exp

distclean: clean
	rm -f Makefile
